spring:
  application:
    name: yu-pao
  datasource:
    url: jdbc:mysql://localhost:3306/stone?serverTimezone=Asia/Shanghai
    username: root
    password: 121211
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    timeout: 3600
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
knife4j:
  enable: true
  openapi:
    title: 用户中心
    description: 这是接口文档
    email: xxx@qq.com
    concat: stone
    version: v2.0
    group:
      test1:
        group-name: 用户
        api-rule: package
        api-rule-resources:
          - com.yupi.yupao.controller